"""Add pm_completion history table

Revision ID: 047d8a314d63
Revises: 86200fdc6d14
Create Date: 2026-05-19 13:05:17.127030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047d8a314d63'
down_revision = '86200fdc6d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pm_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pm_id', sa.Integer(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checklist_results', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pm_id'], ['pm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pm_completion')
    # ### end Alembic commands ###
