"""Initial migration

Revision ID: 251c08cf95fd
Revises: f345edc66e35
Create Date: 2026-02-19 20:06:33.778398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '251c08cf95fd'
down_revision = 'f345edc66e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_pm')
    with op.batch_alter_table('pm', schema=None) as batch_op:
        batch_op.alter_column('main_equipment',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('sub_equipment',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')

    with op.batch_alter_table('pm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('sub_equipment',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('main_equipment',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    op.create_table('_alembic_tmp_pm',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('main_equipment', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sub_equipment', sa.VARCHAR(length=255), nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_done', sa.DATE(), nullable=True),
    sa.Column('next_due', sa.DATE(), nullable=True),
    sa.Column('checklist', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
