"""Update PM relationship backref.

Revision ID: 86200fdc6d14
Revises: 8f49a1aa16ae
Create Date: 2026-02-21 10:01:21.853530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86200fdc6d14'
down_revision = '8f49a1aa16ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pm_assignments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pm_assignments',
    sa.Column('pm_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pm_id'], ['pm.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('pm_id', 'user_id')
    )
    # ### end Alembic commands ###
