"""Add assigned_user_id to PM

Revision ID: 8f49a1aa16ae
Revises: 251c08cf95fd  # Adjust if your previous revision ID is different
Create Date: 2026-02-21  # Adjust date if needed

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8f49a1aa16ae'
down_revision = '251c08cf95fd'  # Adjust to your previous revision ID
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pm_assigned_user_id', 'users', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pm_assigned_user_id', type_='foreignkey')
        batch_op.drop_column('assigned_user_id')
    # ### end Alembic commands ###