"""Add Equipment table with equipment_id

Revision ID: a00920c39834
Revises: 
Create Date: 2026-05-25 12:00:15.981096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00920c39834'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_id', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['equipment_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('equipment_id')

    # ### end Alembic commands ###
