"""Add email column

Revision ID: f345edc66e35
Revises: 1bc9322aa05e
Create Date: 2026-02-18 23:27:41.516099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f345edc66e35'
down_revision = '1bc9322aa05e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm', schema=None) as batch_op:
        batch_op.alter_column('main_equipment',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('sub_equipment',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('pm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('sub_equipment',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('main_equipment',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
