"""Add PM assignments table

Revision ID: fd1e88ce9486
Revises: 
Create Date: 2026-02-18 12:04:05.685878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1e88ce9486'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pm_assignments',
    sa.Column('pm_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pm_id'], ['pm.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('pm_id', 'user_id')
    )
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.alter_column('qty',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('min_stock',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('max_stock',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'999'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.alter_column('max_stock',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'999'"))
        batch_op.alter_column('min_stock',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('qty',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('pm_assignments')
    # ### end Alembic commands ###
